/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Пароль принят и отложен: аккаунт создаётся только после ввода кода.
     */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Проверяет пароль и отправляет код: сессия появляется только после кода.
     */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/otp/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify Otp
     * @description Проверяет код и завершает вход или регистрацию.
     */
    post: operations['verify_otp_api_v1_auth_otp_verify_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh
     * @description Один обмен refresh на новый access указанного назначения и новый refresh.
     */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Отзывает сессию и удаляет cookie. Ответ одинаков независимо от результата.
     */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/oauth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Providers
     * @description Какие кнопки показывать: провайдер без client_id считается выключенным.
     */
    get: operations['list_providers_api_v1_auth_oauth_providers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/oauth/{provider}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Oauth Start */
    get: operations['oauth_start_api_v1_auth_oauth__provider__start_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/oauth/{provider}/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Oauth Callback
     * @description Возврат от провайдера: обмен кода, поиск или создание пользователя, сессия.
     */
    get: operations['oauth_callback_api_v1_auth_oauth__provider__callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Projects */
    get: operations['list_projects_api_v1_projects_get'];
    put?: never;
    /** Create Project */
    post: operations['create_project_api_v1_projects_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations['get_project_api_v1_projects__project_id__get'];
    put?: never;
    post?: never;
    /** Delete Project */
    delete: operations['delete_project_api_v1_projects__project_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/board/columns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Columns
     * @description Только чтение.
     *
     *     Раньше здесь создавались колонки по умолчанию, и два параллельных запроса
     *     к пустой доске делали два набора. Набор создаётся при создании проекта,
     *     а старым проектам он добавлен миграцией.
     */
    get: operations['list_columns_api_v1_board_columns_get'];
    put?: never;
    /** Create Column */
    post: operations['create_column_api_v1_board_columns_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/board/columns/{column_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Column
     * @description Задачи не удаляются вместе с колонкой: column_id обнуляется (SET NULL).
     */
    delete: operations['delete_column_api_v1_board_columns__column_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Column
     * @description Переименование и перемещение колонки между соседями.
     */
    patch: operations['update_column_api_v1_board_columns__column_id__patch'];
    trace?: never;
  };
  '/api/v1/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description Список задач проекта с поиском и фильтрами.
     */
    get: operations['list_tasks_api_v1_tasks_get'];
    put?: never;
    /** Create Task */
    post: operations['create_task_api_v1_tasks_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Tasks
     * @description Поиск по всем проектам пользователя: заголовок, описание, содержимое.
     */
    get: operations['search_tasks_api_v1_tasks_search_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Task */
    delete: operations['delete_task_api_v1_tasks__task_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Task
     * @description Частичное обновление задачи.
     *
     *     `If-Match` с номером версии из последнего прочитанного ответа делает запись
     *     условной: правка, сделанная на устаревшем снимке, отвергается вместо того,
     *     чтобы молча затереть изменение из другой вкладки. Без заголовка проверки
     *     нет — старые клиенты продолжают работать как прежде.
     */
    patch: operations['update_task_api_v1_tasks__task_id__patch'];
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Move Task
     * @description Перетаскивание: задача встаёт между указанными соседями.
     */
    post: operations['move_task_api_v1_tasks__task_id__move_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tags */
    get: operations['list_tags_api_v1_tags_get'];
    put?: never;
    /** Create Tag */
    post: operations['create_tag_api_v1_tags_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tags/{tag_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Tag */
    delete: operations['delete_tag_api_v1_tags__tag_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations['list_categories_api_v1_categories_get'];
    put?: never;
    /** Create Category */
    post: operations['create_category_api_v1_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Category
     * @description Задачи сохраняются: внешний ключ обнуляется (ON DELETE SET NULL).
     */
    delete: operations['delete_category_api_v1_categories__category_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload File */
    post: operations['upload_file_api_v1_files_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/{attachment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download File
     * @description Доступ даёт либо подписанная ссылка, либо access token владельца.
     */
    get: operations['download_file_api_v1_files__attachment_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/assist': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assist
     * @description Обращение к модели платное, поэтому лимит считается по пользователю.
     *
     *     Сессия проверяется короткой отдельной сессией БД: ожидание внешней
     *     модели не должно удерживать SQL-соединение из пула.
     */
    post: operations['assist_api_v1_ai_assist_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/analytics/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Summary */
    get: operations['summary_api_v1_analytics_summary_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notifications/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Settings */
    get: operations['read_settings_api_v1_notifications_settings_get'];
    /** Update Settings */
    put: operations['update_settings_api_v1_notifications_settings_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notifications/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send Test
     * @description Проверка связи: без неё неверный chat_id обнаружился бы только в дедлайн.
     */
    post: operations['send_test_api_v1_notifications_test_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/task-attributes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Attribute Meta */
    get: operations['list_attribute_meta_api_v1_task_attributes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/task-attributes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Attribute Meta */
    post: operations['create_attribute_meta_api_v1_admin_task_attributes_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/task-attributes/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Attribute Meta */
    delete: operations['delete_attribute_meta_api_v1_admin_task_attributes__code__delete'];
    options?: never;
    head?: never;
    /**
     * Update Attribute Meta
     * @description Изменение типа или обязательности допускается только для совместимых данных.
     */
    patch: operations['update_attribute_meta_api_v1_admin_task_attributes__code__patch'];
    trace?: never;
  };
  '/api/v1/user/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Current User
     * @description Кто вошёл: клиенту нужен id для ключей кэша и разделения аккаунтов.
     */
    get: operations['read_current_user_api_v1_user_me_get'];
    put?: never;
    post?: never;
    /**
     * Delete Account
     * @description Удаление аккаунта: подтверждение личности, отзыв сессий, каскад.
     *
     *     Обработку резервных копий и журналов нужно согласовать с политикой хранения:
     *     один DELETE из `users` не реализует весь процесс.
     */
    delete: operations['delete_account_api_v1_user_me_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/export-data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export User Data
     * @description Синхронный экспорт небольшого объёма.
     *
     *     Связи загружаются явно через selectinload: при lazy="raise" обращение к
     *     `p.tasks` иначе подняло бы исключение, а не скрытый SQL. Хеши паролей и
     *     действующие токены в экспорт не попадают.
     *
     *     Выгрузка должна позволять восстановить список дел: раньше в неё попадали
     *     только id, атрибуты и отметки времени задачи, то есть ни заголовка, ни
     *     текста, ни срока в ней не было. Ссылки на вложения не подписываются —
     *     подпись живёт час, а выгрузка хранится долго; вместо неё идёт перечень
     *     файлов с постоянными идентификаторами.
     */
    get: operations['export_user_data_api_v1_user_export_data_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Password
     * @description Смена пароля отзывает все сессии: оставшиеся access-токены и открытые
     *     SSE-потоки перестают давать доступ, требуется повторный вход.
     */
    post: operations['change_password_api_v1_user_change_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/delete-code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request Delete Code
     * @description Код подтверждения удаления аккаунта на адрес владельца.
     *
     *     Нужен аккаунтам без пароля: у входа через OAuth подтверждать нечего, а
     *     удаление данных обязано требовать свежего подтверждения личности. Код
     *     привязан к действию: цель `delete_account` не принимается на
     *     /auth/otp/verify и сессию не создаёт.
     */
    post: operations['request_delete_code_api_v1_user_delete_code_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tasks Sse Stream */
    get: operations['tasks_sse_stream_api_v1_tasks_stream_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccessTokenResponse */
    AccessTokenResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Token Type
       * @default Bearer
       * @constant
       */
      token_type: 'Bearer';
    };
    /** AnalyticsCategorySlice */
    AnalyticsCategorySlice: {
      /** Name */
      name: string;
      /** Color */
      color: string;
      /** Total */
      total: number;
      /** Completed */
      completed: number;
    };
    /** AnalyticsPoint */
    AnalyticsPoint: {
      /** Date */
      date: string;
      /** Created */
      created: number;
      /** Completed */
      completed: number;
    };
    /** AnalyticsResponse */
    AnalyticsResponse: {
      /** Range Days */
      range_days: number;
      /** Total */
      total: number;
      /** Completed */
      completed: number;
      /** Overdue */
      overdue: number;
      /** Due Soon */
      due_soon: number;
      /** Completion Rate */
      completion_rate: number;
      /** Daily */
      daily: components['schemas']['AnalyticsPoint'][];
      /** By Category */
      by_category: components['schemas']['AnalyticsCategorySlice'][];
    };
    /** AssistRequest */
    AssistRequest: {
      /**
       * Action
       * @enum {string}
       */
      action: 'ideas' | 'summarize' | 'decompose' | 'rewrite';
      /** Text */
      text: string;
    };
    /** AssistResponse */
    AssistResponse: {
      /** Text */
      text: string;
      /** Items */
      items: string[];
      /**
       * Provider
       * @enum {string}
       */
      provider: 'anthropic' | 'stub';
      /** Model */
      model?: string | null;
    };
    /** AttachmentResponse */
    AttachmentResponse: {
      /** Id */
      id: string;
      /** Url */
      url: string;
      /** Filename */
      filename: string;
      /** Content Type */
      content_type: string;
      /** Size Bytes */
      size_bytes: number;
    };
    /** BoardColumnCreate */
    BoardColumnCreate: {
      /** Project Id */
      project_id: number;
      /** Title */
      title: string;
      /**
       * Is Done Column
       * @default false
       */
      is_done_column: boolean;
    };
    /** BoardColumnResponse */
    BoardColumnResponse: {
      /** Id */
      id: number;
      /** Project Id */
      project_id: number;
      /** Title */
      title: string;
      /** Position */
      position: number;
      /** Is Done Column */
      is_done_column: boolean;
    };
    /** BoardColumnUpdate */
    BoardColumnUpdate: {
      /** Title */
      title?: string | null;
      /** Is Done Column */
      is_done_column?: boolean | null;
      /** Before Id */
      before_id?: number | null;
      /** After Id */
      after_id?: number | null;
    };
    /** Body_upload_file_api_v1_files_post */
    Body_upload_file_api_v1_files_post: {
      /** File */
      file: string;
    };
    /** CategoryCreate */
    CategoryCreate: {
      /** Name */
      name: string;
      /**
       * Color
       * @default #6366f1
       */
      color: string;
    };
    /** CategoryResponse */
    CategoryResponse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Color */
      color: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** CurrentUserResponse */
    CurrentUserResponse: {
      /** Id */
      id: number;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Is Admin */
      is_admin: boolean;
      /** Display Name */
      display_name?: string | null;
      /** Avatar Url */
      avatar_url?: string | null;
      /** Has Password */
      has_password: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * DeleteAccountRequest
     * @description Повторное подтверждение личности для чувствительной операции.
     *
     *     Пароль есть не у всех: аккаунт, созданный через OAuth, иначе невозможно
     *     удалить вовсе. Для него подтверждением служит одноразовый код на
     *     подтверждённый адрес, запрошенный отдельно и привязанный к этому действию.
     *     Пропускать проверку для OAuth-аккаунтов нельзя: удаление данных должно
     *     требовать свежего подтверждения личности.
     */
    DeleteAccountRequest: {
      /** Password */
      password?: string;
      /** Code */
      code?: string;
    };
    /**
     * DeleteCodeChallengeResponse
     * @description Код подтверждения удаления аккаунта отправлен.
     *
     *     Отдельный тип, а не расширение OtpChallengeResponse: цель этого кода не
     *     входит в допустимые значения /auth/otp/verify, и контракт входа не должен
     *     объявлять её как возможный ответ.
     */
    DeleteCodeChallengeResponse: {
      /**
       * Otp Required
       * @default true
       * @constant
       */
      otp_required: true;
      /**
       * Purpose
       * @default delete_account
       * @constant
       */
      purpose: 'delete_account';
      /** Expires In */
      expires_in: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MetaFieldCreate */
    MetaFieldCreate: {
      /** Code */
      code: string;
      /** Title */
      title: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'string' | 'boolean' | 'date';
      /**
       * Is Required
       * @default false
       */
      is_required: boolean;
    };
    /** MetaFieldResponse */
    MetaFieldResponse: {
      /** Code */
      code: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'string' | 'boolean' | 'date';
      /** Is Required */
      is_required: boolean;
      /** Title */
      title: string;
    };
    /** NotificationPrefsSchema */
    NotificationPrefsSchema: {
      /**
       * Email Enabled
       * @default true
       */
      email_enabled: boolean;
      /**
       * Telegram Enabled
       * @default false
       */
      telegram_enabled: boolean;
      /** Telegram Chat Id */
      telegram_chat_id?: string | null;
      /**
       * Lead Time Minutes
       * @default 60
       */
      lead_time_minutes: number;
    };
    /** OAuthProvidersResponse */
    OAuthProvidersResponse: {
      /** Providers */
      providers: ('google' | 'github')[];
    };
    /**
     * OtpChallengeResponse
     * @description Ответ на шаг «пароль принят»: сессии ещё нет, нужен код из письма.
     */
    OtpChallengeResponse: {
      /**
       * Otp Required
       * @default true
       * @constant
       */
      otp_required: true;
      /**
       * Purpose
       * @enum {string}
       */
      purpose: 'login' | 'register';
      /** Expires In */
      expires_in: number;
    };
    /** OtpVerifyRequest */
    OtpVerifyRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Code */
      code: string;
      /**
       * Purpose
       * @enum {string}
       */
      purpose: 'login' | 'register';
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * RefreshRequest
     * @description `user_id` клиент не передаёт: он берётся из серверной записи сессии.
     */
    RefreshRequest: {
      /**
       * Purpose
       * @enum {string}
       */
      purpose: 'api' | 'sse';
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** TagCreate */
    TagCreate: {
      /** Name */
      name: string;
      /**
       * Color
       * @default #64748b
       */
      color: string;
    };
    /** TagResponse */
    TagResponse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Color */
      color: string;
    };
    /** TaskCreate */
    TaskCreate: {
      /** Project Id */
      project_id: number;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Content */
      content?: {
        [key: string]: unknown;
      } | null;
      /** Due At */
      due_at?: string | null;
      /** Column Id */
      column_id?: number | null;
      /** Category Id */
      category_id?: number | null;
      /** Tag Ids */
      tag_ids?: number[];
      /** Attributes */
      attributes?: {
        [key: string]: string | boolean | null;
      };
    };
    /**
     * TaskMove
     * @description Перетаскивание: целевая колонка и соседи в ней.
     */
    TaskMove: {
      /** Column Id */
      column_id?: number | null;
      /** Before Id */
      before_id?: number | null;
      /** After Id */
      after_id?: number | null;
    };
    /** TaskResponse */
    TaskResponse: {
      /** Id */
      id: number;
      /** Project Id */
      project_id: number;
      /** Column Id */
      column_id: number | null;
      /** Category Id */
      category_id: number | null;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Content */
      content: {
        [key: string]: unknown;
      } | null;
      /** Position */
      position: number;
      /** Due At */
      due_at: string | null;
      /** Completed At */
      completed_at: string | null;
      /** Attributes */
      attributes: {
        [key: string]: string | boolean;
      };
      /** Tags */
      tags?: components['schemas']['TagResponse'][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /**
     * TaskUpdate
     * @description Частичное обновление: поле меняется, только если явно передано.
     *
     *     `attributes` заменяются целиком — JSONB присваивается новым словарём.
     *
     *     Null принимается только там, где очистка значения осмысленна: описание,
     *     содержимое, срок, колонка и категория. Для заголовка, тегов, атрибутов и
     *     признака выполнения null операцией не является — раньше он молча
     *     игнорировался, и клиент не мог отличить его от применённого изменения.
     */
    TaskUpdate: {
      /** Title */
      title?: string;
      /** Description */
      description?: string | null;
      /** Content */
      content?: {
        [key: string]: unknown;
      } | null;
      /** Due At */
      due_at?: string | null;
      /** Column Id */
      column_id?: number | null;
      /** Category Id */
      category_id?: number | null;
      /** Tag Ids */
      tag_ids?: number[];
      /** Attributes */
      attributes?: {
        [key: string]: string | boolean | null;
      };
      /** Completed */
      completed?: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OtpChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OtpChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_otp_api_v1_auth_otp_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OtpVerifyRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessTokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessTokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_providers_api_v1_auth_oauth_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OAuthProvidersResponse'];
        };
      };
    };
  };
  oauth_start_api_v1_auth_oauth__provider__start_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  oauth_callback_api_v1_auth_oauth__provider__callback_get: {
    parameters: {
      query?: {
        code?: string;
        state?: string;
        error?: string;
      };
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_projects_api_v1_projects_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_project_api_v1_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_columns_api_v1_board_columns_get: {
    parameters: {
      query: {
        project_id: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoardColumnResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_column_api_v1_board_columns_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BoardColumnCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoardColumnResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_column_api_v1_board_columns__column_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        column_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_column_api_v1_board_columns__column_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        column_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BoardColumnUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoardColumnResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_tasks_api_v1_tasks_get: {
    parameters: {
      query: {
        project_id: number;
        /** @description Полнотекстовый поиск */
        q?: string | null;
        tag_id?: number[] | null;
        category_id?: number | null;
        column_id?: number | null;
        due_before?: string | null;
        completed?: boolean | null;
        /** @description JSON-фрагмент для containment-поиска по JSONB, например {"billable":true} */
        attributes_contains?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_task_api_v1_tasks_post: {
    parameters: {
      query?: never;
      header?: {
        'Idempotency-Key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_tasks_api_v1_tasks_search_get: {
    parameters: {
      query: {
        q: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_task_api_v1_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_task_api_v1_tasks__task_id__patch: {
    parameters: {
      query?: never;
      header?: {
        'If-Match'?: string | null;
      };
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  move_task_api_v1_tasks__task_id__move_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskMove'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_tags_api_v1_tags_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagResponse'][];
        };
      };
    };
  };
  create_tag_api_v1_tags_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TagCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_tag_api_v1_tags__tag_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tag_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponse'][];
        };
      };
    };
  };
  create_category_api_v1_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_api_v1_categories__category_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_file_api_v1_files_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_api_v1_files_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttachmentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  download_file_api_v1_files__attachment_id__get: {
    parameters: {
      query?: {
        exp?: string;
        sig?: string;
      };
      header?: never;
      path: {
        attachment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  assist_api_v1_ai_assist_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssistRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssistResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  summary_api_v1_analytics_summary_get: {
    parameters: {
      query?: {
        days?: number;
        project_id?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnalyticsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_settings_api_v1_notifications_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationPrefsSchema'];
        };
      };
    };
  };
  update_settings_api_v1_notifications_settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NotificationPrefsSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationPrefsSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  send_test_api_v1_notifications_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_attribute_meta_api_v1_task_attributes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaFieldResponse'][];
        };
      };
    };
  };
  create_attribute_meta_api_v1_admin_task_attributes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MetaFieldCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaFieldResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_attribute_meta_api_v1_admin_task_attributes__code__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_attribute_meta_api_v1_admin_task_attributes__code__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MetaFieldCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaFieldResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_current_user_api_v1_user_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentUserResponse'];
        };
      };
    };
  };
  delete_account_api_v1_user_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_user_data_api_v1_user_export_data_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  change_password_api_v1_user_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  request_delete_code_api_v1_user_delete_code_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteCodeChallengeResponse'];
        };
      };
    };
  };
  tasks_sse_stream_api_v1_tasks_stream_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
